# Generated by Django 4.1.4 on 2023-04-01 20:33

from django.db import migrations, models
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_duration_alter_project_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('team', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('quick_description', models.TextField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, default='coming_soon.png', null=True, upload_to='')),
                ('feature_video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('source_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(blank=True, to='projects.tag')),
            ],
        ),
    ]
