# Generated by Django 4.1.4 on 2023-04-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_feature_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature_project',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='overview',
        ),
        migrations.AddField(
            model_name='feature_project',
            name='development_enviroment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='development_enviroment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
