# Generated by Django 4.1.4 on 2023-04-02 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_description_feature_project_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development_Enviroment',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature_project',
            name='development_enviroment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='development_enviroment',
        ),
    ]
