# Generated by Django 4.1.4 on 2023-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_development_enviroment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_project',
            name='development',
            field=models.ManyToManyField(blank=True, to='projects.development_enviroment'),
        ),
        migrations.AddField(
            model_name='project',
            name='development',
            field=models.ManyToManyField(blank=True, to='projects.development_enviroment'),
        ),
    ]
