# Generated by Django 4.1.4 on 2023-04-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_contactform_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
